baseUrl: http://localhost
swagger:
    resourcePackage: com.isortegah.rest.resources
server:
  applicationConnectors:
    - type: http
      port: 8080
aws:
  credentialProvider: File
  region: US_EAST_1